### PR TITLE
Add Zerobuf::notifyChanged() callback

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
After the change is not possible due to non-const getters which return references to data in the allocator. So notifyChanging() then?

**Comment by tribal-tec** [comment]
ping?

**Comment by hernando** [comment]
It's better yes

**Comment by tribal-tec** [comment]
Updated

**Comment by eile** [comment]
+1

Oh god, the merge conflicts on my nested branch :-/

**Comment by bilgili** [comment]
Would not it be good idea to provide the changing item name as a const parameter ? ( Or it is useless ? )

**Comment by eile** [comment]
We can add it when we have a use case.

**Comment by tribal-tec** [comment]
Then a getItemByIndex/Name() would be handy as well, otherwise the application has to index and do if-else to call the correct set/get for the changed item. As the API is far from final, I would also reserve that for later.

**Pull request merged**
