### PR TITLE
Remove set/getString method for non-string dynamic members

### PR DESCRIPTION
**Pull request by tribal-tec**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Not sure I got the cleanup intention right. Only needed for 'real' strings imo, hence removed for all other array/vector types.

**Comment by rdumusc** [comment]
To me this change makes sense. I wonder if we could go one step further and remove everything except the string getters for the string type. Are the typedef vector<char>, etc.. needed?

**Comment by tribal-tec** [comment]
Not needed also it seems. The zerobuf::Vector is needed in theory for guaranteeing zero-copy.

**Comment by eile** [comment]
Agreed on the zero-copy path. Not sure how it looks for the equivalent of set( T*, size )?

**Comment by tribal-tec** [comment]
Ahhh, that merge went too fast. Had the ones @rdumusc suggested not pushed yet...

**Pull request merged**
