### PR TITLE
fixed using "import *"

### PR DESCRIPTION
**Pull request by mgeplf**
* fixed trailing ';'
* fixed builtin 'file' being used

### CODE REVIEW

**Comment by rdumusc** [comment]
+1 thanks, these are good cleanups! Interestingly you fixed the parts I had left aside in my (almost full) re-factoring of this file. What is the issue with the builtin 'file' being used? In my new branch I keep using variables named 'file' in multiple placed and didn't have any issues, should I rename all occurences to _file?

**Comment by mgeplf** [comment]
You're working on a cleanup? We shouldn't duplicate work then, b/c at the moment it's too global heavy, and I think that should be fixed.

Python allows you to overwrite any of the builtin function names, and 'file' (due to historical reason) is one of them, ie: https://docs.python.org/2/library/functions.html#file

The full list is here:
https://docs.python.org/2/library/functions.html

Fortunately, 'file' is being deprecated in py3.

**Comment by rdumusc** [comment]
Yes, I rewrote almost everything using classes instead of globals. I wanted to submit a PR later today. So, I gather that overwriting file is not a big deal, and I will keep my variables names 'file'.

**Comment by mgeplf** [comment]
Cool, I will not do it then.
I would recommend against using it, personally.  Consider it a reserved keyword for now.

**Comment by rdumusc** [comment]
OK will do. If I had known you were willing to do the refactoring I would have left it to the real python expert ;-)

**Comment by mgeplf** [comment]
ha, 'real python expert' is not a title I claim

I have a compulsion to fix things.

**Pull request merged**
