### PR TITLE
Add presentation

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
retest this please.

**Comment by eile** [comment]
ping

**Comment by bilgili** [comment]
No boost interprocess ?

**Comment by eile** [comment]
@bilgili : Not sure what you're getting at. This is a presentation which was forgotten in my fork since Aug describing the current state.

**Comment by bilgili** [comment]
@eile: I thought you were updating the technical documentation for future plan of the project in key file. Thats why I was suprised no mentioning of boost. But if it is only representing the current state thats ok.

**Comment by bilgili** [comment]
And, of course boost interprocess is not a must, but to be looked at.

**Comment by tribal-tec** [comment]
+1

**Pull request merged**
