### PR TITLE
Pretty-format JSON schema

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by eile** [comment]
screen shot 2017-01-25 at 12 08 26

**Comment by rdumusc** [comment]
+1, pretty-format is better! You need to adapt the unit tests as well + add changelog entry.

**Comment by eile** [comment]
Working on the test already, but something weird is going on there (see below). I did not think Changelog necessary?

```
/Users/eilemann/Software/stable/ZeroBuf/tests/jsonSerialization.cpp:277: error: in "json_schema_empty": check test::TestEmpty::ZEROBUF_SCHEMA() == R"({
    "$schema": "http://json-schema.org/schema#",
    "title": "TestEmpty",
    "description": "Class TestEmpty of namespace ['test']",
    "type": "object",
    "additionalProperties": false
})" has failed [{
    "$schema": "http://json-schema.org/schema#",
    "title": "TestEmpty",
    "description": "Class TestEmpty of namespace ['test']",
    "type": "object",
    "additionalProperties": false
} != {
    "$schema": "http://json-schema.org/schema#",
    "title": "TestEmpty",
    "description": "Class TestEmpty of namespace ['test']",
    "type": "object",
    "additionalProperties": false
}]```

**Comment by rdumusc** [comment]
As you wish ;-) I don't know what is the criteria for a necessary Changelog entry, but I also see no reason to omit it: the behavior is modified, and it is nice to have an up-to-date a document listing the progress happening in the project. I don't know about the string comparison issue, they look identical from what you posted.

**Comment by eile** [comment]
Found the string thing. The JSON dump created trailing whitespace.

**Pull request merged**
